[extension]
name = "pg_extra_time"
version = "1.1.2"
license = "postgresql"
repository = "https://github.com/bigsmoke/pg_extra_time"
description = "The pg_extra_time PostgreSQL extension contains some date time functions and operators that, in the opinion of the extension author, ought to be part of the PostgreSQL standard distribution."
homepage = "https://blog.bigsmoke.us/tag/pg_extra_time"
documentation = "https://github.com/bigsmoke/pg_extra_time"

[build]
postgres_version = "15"
platform = "linux/amd64"
