[extension]
name = "ApacheAGE"
version = "1.4.0"
license = "apache_2_0"
repository = "https://github.com/apache/age"
description = "Apache AGE is a PostgreSQL Extension that provides graph database functionality. AGE is an acronym for A Graph Extension, and is inspired by Bitnine's fork of PostgreSQL 10, AgensGraph, a multi-model database. The project's goal is to create a single storage that can handle relational and graph model data so that users can use standard ANSI SQL along with openCypher, the Graph query language. A graph consists of a set of vertices (also called nodes) and edges, where each individual vertex and edge possesses a map of properties. A vertex is the basic object of a graph, that can exist independently of everything else in the graph. An edge creates a directed connection between two vertices. A graph database is composed of vertices and edges. This type of database is useful when the meaning is in the relationships between the data. Relational databases can easily handle direct relationships, but indirect relationships are more difficult to deal with in relational databases. A graph database stores relationship information as a first-class entity. Apache AGE gives you the best of both worlds, simultaneously."
homepage = "https://github.com/apache/age/tree/master"
documentation = "https://github.com/apache/age"

[build]
postgres_version = "15"
platform = "linux/amd64"
