[extension]
name = "citus"
version = "12.1.2"
license = "agpl_3"
repository = "https://github.com/citusdata/citus"
description = "Citus horizontally scales PostgreSQL across commodity servers using sharding and replication. Its query engine parallelizes incoming SQL queries across these servers to enable real-time responses on large datasets."
homepage = "https://www.citusdata.com"
documentation = "https://github.com/citusdata/citus"

[build]
postgres_version = "15"
platform = "linux/amd64"
