[extension]
name = "pg_readme"
version = "0.6.5"
license = "postgresql"
repository = "https://github.com/bigsmoke/pg_readme"
description = "The pg_readme PostgreSQL extension provides functions to generate a README.md document for a database extension or schema, based on COMMENT objects found in the pg_description system catalog."
homepage = "https://blog.bigsmoke.us/tag/pg_readme"
documentation = "https://github.com/bigsmoke/pg_readme"

[build]
postgres_version = "15"
platform = "linux/amd64"
