[extension]
name = "pg_uuidv7"
version = "1.4.0"
license = "open_source"
repository = "https://github.com/fboulnois/pg_uuidv7"
description = "Create UUIDv7 values in Postgres"
homepage = "https://github.com/fboulnois/pg_uuidv7"
documentation = "https://github.com/fboulnois/pg_uuidv7"

[build]
postgres_version = "15"
platform = "linux/amd64"
