[extension]
name = "pgTAP"
version = "1.3.2"
license = "PostgreSQL"
repository = "https://github.com/theory/pgtap"
description = "pgTAP is a suite of database functions that make it easy to write TAP-emitting unit tests in psql scripts or xUnit-style test functions."
homepage = "https://pgtap.org/"
documentation = "https://github.com/theory/pgtap"

[build]
postgres_version = "15"
platform = "linux/amd64"
