[extension]
name = "pg_text_semver"
version = "0.1.5"
license = "postgresql"
repository = "https://github.com/bigsmoke/pg_text_semver"
description = "The pg_text_semver extension offers a \"semver\" DOMAIN type based on Postgres' built-in \"text\" type."
homepage = "https://blog.bigsmoke.us/tag/pg_text_semver"
documentation = "https://github.com/bigsmoke/pg_text_semver"

[build]
postgres_version = "15"
platform = "linux/amd64"
