[extension]
name = "pg_stat_kcache"
version = "2.2.3"
license = "postgresql"
repository = "http://github.com/powa-team/pg_stat_kcache/"
description = "An extension gathering CPU and disk acess statistics"
homepage = "http://github.com/powa-team/pg_stat_kcache/"
documentation = "http://github.com/powa-team/pg_stat_kcache/"

[build]
postgres_version = "15"
platform = "linux/amd64"
