[extension]
name = "orafce"
version = "4.9.0"
license = "PostgreSQL"
repository = "https://github.com/orafce/orafce"
description = "This module allows use a well known Oracle's functions and packages inside PostgreSQL"
homepage = "http://www.pgsql.cz/index.php/Oracle_functionality_%28en%29"
documentation = "https://github.com/orafce/orafce"

[build]
postgres_version = "15"
platform = "linux/amd64"
