[extension]
name = "pg_curl"
version = "2.2.2"
license = "mit"
repository = "https://github.com/RekGRpth/pg_curl"
description = "PostgreSQL cURL allows most curl actions, including data transfer with URL syntax via HTTP, HTTPS, FTP, FTPS, GOPHER, TFTP, SCP, SFTP, SMB, TELNET, DICT, LDAP, LDAPS, FILE, IMAP, SMTP, POP3, RTSP and RTMP"
homepage = "https://github.com/RekGRpth/pg_curl"
documentation = "https://github.com/RekGRpth/pg_curl"

[build]
postgres_version = "15"
platform = "linux/amd64"
