[extension]
name = "plpgsql_check"
version = "2.7.0"
license = "bsd"
repository = "https://github.com/okbob/plpgsql_check/"
description = "The plpgsql_check is PostgreSQL extension with functionality for direct or indirect extra validation of functions in plpgsql language. It verifies a validity of SQL identifiers used in plpgsql code. It try to identify a performance issues. Modern versions has integrated profiler. The table and function dependencies can be displayed"
homepage = "https://github.com/okbob/plpgsql_check/"
documentation = "https://github.com/okbob/plpgsql_check/"

[build]
postgres_version = "15"
platform = "linux/amd64"
